image: Ubuntu2204  # Используйте Ubuntu, если Ubuntu2204 не работает

environment:
  nodejs_version: "20"  # Указываем версию Node.js

branches:
  only:
    - main  # Ветка git

cache:
  - node_modules -> yarn.lock  # Кешируем node_modules

install:
  - nvm install $nodejs_version  # Устанавливаем Node.js
  - yarn  # Устанавливаем зависимости

build: off  # Отключаем встроенную сборку MSBuild

build_script:
  - yarn build  # Сборка проекта

test_script:
  - yarn lint
  - yarn test --passWithNoTests

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name "AppVeyor"
  - git config --global user.email "ci@appveyor.com"
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>" --no-history
